baseURL: "https://j-yang-econ.github.io/"
title: Jiayi Yang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Papers
      url: papers/
      weight: 1

params:
  description: "Research on unconventional monetary policy, negative interest rates, and distributional effects of monetary policy."
  author: Jiayi Yang
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["papers"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Jiayi Yang
    subtitle: "I am a PhD graduate in Economics from Queensland University of Technology, Australia, where I completed my doctoral studies under the supervision of Professor Pedro Gomis-Porqueras. 
    
    
    My research lies at the intersection of monetary economics and macroeconomics, with a focus on unconventional monetary policy, the bank lending channel of monetary policy transmission, and the distributional effects of monetary policy. My work is primarily empirical.
    

    **I am currently on the academic job market.**"

    buttons:
      - name: Papers
        url: papers/

  socialIcons:
    - name: CV
      url: files/CV.pdf
    - name: Email
      url: mailto:jiayi.yang.econ@outlook.com
    - name: Google Scholar
      url: https://scholar.google.com/
    - name: GitHub
      url: https://github.com/J-Yang-Econ


  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Jiayi Yang"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
